### ISSUE TITLE
[Playwright + Cucumber-JS] Failed tests are displayed as broken.

### ISSUE THREAD

**Issue by Zychkov** [allure-framework/allure-js#1155]
This bug is only relevant when using expect from Playwright.

**To Reproduce**
Scenario:
```gherkin
Feature: Allure
  Feature's description

  @example @tms=ABC-222 @issue=ABC-333
  Scenario Outline: Allure Tests
    Given The sum of the numbers <a> and <b> must be equal to <c>

    Examples:
      | a | b | c |
      | 1 | 2 | 3 |
      | 2 | 2 | 4 |

    Examples:
      | a | b | c |
      | 3 | 2 | 5 |
      | 4 | 2 | 7 |
```
implementation:
```JavaScript
import {Given} from "@cucumber/cucumber";
import {expect} from "@playwright/test";

Given(/^The sum of the numbers (.*) and (.*) must be equal to (.*)$/,
    async (a, b, c) => {
        expect(Number(a) + Number(b)).toEqual(Number(c));
    });
```
Dependencies:
```
    "@cucumber/cucumber": "^10.9.0",
    "@cucumber/messages": "^24.1.0",
    "@playwright/test": "^1.47.2",
    "allure-commandline": "^2.30.0",
    "allure-cucumberjs": "^3.0.2",
    "allure-js-commons": "^3.0.2"
```

**Expected behavior**
The status of the fallen test should be - Failed. Actual - Broken.

**Screenshots**
![image](https://github.com/user-attachments/assets/95d61ac8-cda2-47cd-a383-d89fd14e9b1a)

**Comment by k-saadii** [comment]
I am still facing the above issue with below Dependencies , The test are marked as Broken instead of Failed ,Can you let me know how can I handle this

 "allure-cucumberjs": "^3.2.1",
 "allure-js-commons": "^3.2.1",
"allure-commandline": "^2.33.0",
"@cucumber/cucumber": "^10.9.0",
 "@cucumber/messages": "^27.2.0",
"@playwright/test": "^1.47.1",
