### ISSUE TITLE
Tracing Options (--steps/--debug/--verbose) No Longer Provide Step-by-Step Output Starting from "allure-codeceptjs v3.0.0-beta.10"

### ISSUE THREAD

**Issue by zyab1ik** [allure-framework/allure-js#1167]
**Describe the bug**
In allure-codeceptjs 3.0.0-beta.10, when running tests with the --steps or --debug options, the expected step-by-step output is no longer shown

**To Reproduce**
1. Run any test with the --steps or --debug option
2. Observe that the expected step-by-step output is not displayed.

**Expected behavior**
Tests should display step-by-step reports with trace options

**Screenshots**
`"allure-codeceptjs": "3.0.0-beta.10":`
<img width="970" alt="image" src="https://github.com/user-attachments/assets/0f0ff8b0-1380-43d7-9e50-a809402c12ee">

`"allure-codeceptjs": "3.0.0-beta.9"`
<img width="1544" alt="image" src="https://github.com/user-attachments/assets/cc6058ae-bff1-4fd8-8ae2-348a1f94dc06">

<img width="1545" alt="image" src="https://github.com/user-attachments/assets/51257448-498f-4430-ac0b-27e92313f744">

**Additional context**
This issue started with allure-codeceptjs version [3.0.0-beta.10](https://github.com/allure-framework/allure-js/commit/60767e951ad5e7507598150af53864bb24e748f0) and persists in the latest version. The expected step-by-step output for the --steps and --debug options does not work

**Comment by baev** [comment]
@zyab1ik Since 3.0.0-beta.10, allure-codeceptjs integration was reworked. Now, it uses a Mocha reporter underneath (taking allure-mocha as a baseline) and enriches the report using some Codeceptjs events. 

I honestly don't know the `--steps` or `--debug` options you're talking about. Could you please elaborate and explain them in more detail?

**Comment by zyab1ik** [comment]
@baev 
In CodeceptJS, there are standard options for debugging tests, such as `--steps`, `--debug`, and `--verbose`. More details can be found in their documentation:
[#debug option](https://codecept.io/advanced/#debug)
[commands](https://codecept.io/commands)

However, when using the Allure adapter together with CodeceptJS above the version `allure-codeceptjs v3.0.0-beta.9`, these options stop working. If you disable the Allure adapter through the config or downgrade the version to allure-codeceptjs `v2.15.1`, the detailed test output in the terminal works fine.

Could you suggest a solution to this? Is there any way to fix it?



P/s 
<img width="875" alt="image" src="https://github.com/user-attachments/assets/bda75c79-5d83-47a3-9163-ae781816f213">

<img width="964" alt="image" src="https://github.com/user-attachments/assets/1285bfe7-cf52-4112-b38d-381ed325de9c">

**Comment by baev** [comment]
@zyab1ik thanks

According to https://github.com/codeceptjs/CodeceptJS/issues/698#issuecomment-327282346, the console output will not work if a custom reporter is used.

Since Allure currently overrides the specified reporter configuration, the options mentioned above will not work. 

The CodeceptJS team suggests using the `mocha-multi` reporter, which will not work with Allure CodeceptJS since it relies on CodeceptJS events as well ( Allure CodeceptJS is a Mocha reporter and CodeceptJS plugin at the same time).

We plan to provide `mocha-multi` functionality in Allure Mocha (so you can add Allure Mocha reporter & proxy events to some 3rd party reporters). Using this feature, it may be possible to enable `codeceptjs/lib/cli` reporter by default, which should fix the issue.

**Comment by delatrie** [comment]
Hi, @zyab1ik
The issue is fixed in allure-codeceptjs@3.0.6. The tracing options should now work out of the box.
