### ISSUE TITLE
[Feature] Group tests by spec file instead of projects (allure-playwright)

### ISSUE THREAD

**Issue by Nav-2d** [allure-framework/allure-js#360]
**Is your feature request related to a problem? Please describe.**
Currently, `allure-playwright` report group the results by projects. 

**Describe the solution you'd like**
Group the results by each spec file.

![Screen Shot 2021-09-14 at 11 29 41 PM](https://user-images.githubusercontent.com/22205721/133382485-abc5f2d5-0aee-4543-9ef1-8134cb0bfe09.png)

**Comment by baev** [comment]
https://github.com/allure-framework/allure-js/pull/1033 will allow you to use the Packages tab to see the tests grouped by test files.

I agree that, by default, the report should show the tests grouped by spec paths and then additionally grouped by describes (if any). The problem is that Allure 2 currently has limitations that prevent the proper implementation of the report this way. The good news is that it's already planned for Allure 3.
