### ISSUE TITLE
Tests in parameterized 'test.describe' block are reported as retries

### ISSUE THREAD

**Issue by mihalichzh** [allure-framework/allure-js#732]
Hi guys!

**Describe the bug**
Tests are unexpectedly reported as retries when wrapped with parameterized describe block.

**To Reproduce**
1. Clone repo https://github.com/mihalichzh/allure_playwright_issue
2. Run tests using 'npx playwright test' 
3. Generate and open allure report

**Expected behavior**
Tests in parameterized describe block are not reported as retries. Each describe block is expected to be treated as a separate test item if parameterized (as it is in native 'html' reporter).

**Additional context**
Reproducible with (at least) playwright 1.34.3/1.36.1 and allure-playwright 2.4.0.

**Playwright html reporter:**
<img width="1068" alt="Screenshot 2023-07-20 at 23 19 16" src="https://github.com/allure-framework/allure-js/assets/39348763/8d6f1e37-c6e0-4f4a-ba5b-ff807f840b69">

**Allure:**
<img width="1330" alt="Screenshot 2023-07-20 at 23 18 38" src="https://github.com/allure-framework/allure-js/assets/39348763/6e349b4a-f98d-4308-a781-fc40aa37eb09">

**Comment by nbaldzhiev** [comment]
I can confirm that tests in a parameterised `describe` block are reported as retried (`"allure-playwright": "^2.5.0",`"@playwright/test": "^1.36.2"`)

This is very confusing because when you open the Tree of the Launch, for the given file you only see the last parameterised run, so it looks like only those tests ran. However, when you click on a given test and go to retries, you actually see these are not really"retries", but are the other parameterised tests. In our case, there's a file with 1 `describe` block, which contains 4 tests and is parameterised against 3 values. In, Allure TestOps launch tree view, this file is reported to have ran 8 tests; but when you click each test and go to retries, there are 2 more tests, which are the other 2 parameterised values (the `describe` block is parameterised against 3 values). We only see the run against the last parameterised value in the launch tree view and the runs against the previous 2 parameterised values are only visible in the "retries" section. So, when we ran against 2 browsers, the launch's tree view showed only 8 ran tests in that file, but in reality 24 tests were ran (2 browsers * 3 parameterised values * 4 tests) - the rest of the tests were only visible in the retries section of each test visible in the launch tree view.
