### ISSUE TITLE
allure-hermione: The "_process" property of WorkerProcess was renamed to "process"

### ISSUE THREAD

**Issue by vitaly-kiselev-qa** [allure-framework/allure-js#853]
**Describe the bug**
The `_process` property of `WorkerProcess` was renamed to `process` in Hermione 8.0:
https://github.com/gemini-testing/hermione/blob/master/src/utils/worker-process.ts#L6

The new name should be used in `allure-hermione`:
https://github.com/allure-framework/allure-js/blob/main/packages/allure-hermione/src/index.ts#L234

**To Reproduce**
1. Install `Hermione 8+` and `allure-hermione`.
2. Run any test.

The error occurs on `worker._process.on`:
> cannot read properties of undefined

The `worker._process` is `undefined`.

**Expected behavior**
No error occurs.

**Desktop:**
- OS: macOS Sonoma 14.2.1
- Chrome
- Version 120.0.6099.109 (Official Build) (x86_64)

**Comment by shadowusr** [comment]
Ideally, the `process` property should not be used at all, since it's a private API of Hermione and may change at any time. As far as I can tell it's used for general-purpose IPC in allure, but you can use any other approach (instance of some other event bus, created and owned as a resource by allure) and will work just fine and without possibility of breaking at any time.

**Comment by epszaw** [comment]
Thank you for the information. Will update the framework compatibility as soon as I have time to do that.
