### ISSUE TITLE
[Cucumber.js] - Using Story metadata duplicates the test in the report

### ISSUE THREAD

**Issue by harmin-parra** [allure-framework/allure-js#999]
**Describe the bug**
Each test gets duplicated in the report when using the `suite` metadata

**To Reproduce**

Feature file:
```
Sample Feature file: Petstore

  Scenario: Add pet
    Given I have a pet store
    When I add a pet
    Then The pet is added

```

Sample step definition: 
```
const assert = require('assert');
const { Given, When, Then, setWorldConstructor } = require('@cucumber/cucumber');
const { CucumberAllureWorld } = require("allure-cucumberjs")
const { LabelName } = require("allure-js-commons");
const axios = require('axios');
const Petstore = require('../../model/petstore');

setWorldConstructor(CucumberAllureWorld)

var id = 543;
var petstore = new Petstore();

Given("I have a pet store", async function() { 
  assert(petstore != null);
});

When('I add a pet', async function() {
  payload = {"id": id, "name": "doggie", "status": "available"};
  this.payload = payload;
  await petstore.post(payload, this)
    .then(res => {
      this.attach(JSON.stringify(res.data), "application/json");
      assert.equal(res.status, 200);
    })
    .catch(err => {
      this.attach(err.toString(), "text/plain");
      assert.fail("The pet was not added");
    });
});

Then('The pet is added', async function() {
  this.epic("REST api");
  this.parentSuite("REST api");
  this.suite("Petstore");
  this.label(LabelName.PACKAGE, "cucumber.features.petstore")
  await petstore.get(id, this)
    .then(res => {
      this.attach(JSON.stringify(res.data), "application/json");
      assert.equal(res.status, 200);
      for( var key in this.payload )
        assert.equal(res.data[key], this.payload[key]);
    })
    .catch(err => {
      this.attach(err.toString(), "text/plain");
      assert.fail("The pet was not added");
    });
});
```

The model:
```
const assert = require('assert');
const axios = require('axios');

headers = {
    'Content-Type': 'application/json',
    'accept': 'application/json'
};

class Petstore {

  get(id, allure) {
    allure.attach("GET https://petstore.swagger.io/v2/pet/" + id, "text/plain");
    return axios.get("https://petstore.swagger.io/v2/pet/" + id);
  }

  post(payload, allure) {
    allure.attach("POST https://petstore.swagger.io/v2/pet/", "text/plain");
    allure.attach(JSON.stringify(payload), "application/json");
    return axios.post("https://petstore.swagger.io/v2/pet/", payload);
  }

  delete(id, allure) {
    allure.attach("DELETE https://petstore.swagger.io/v2/pet/" + id, "text/plain");
    return axios.delete("https://petstore.swagger.io/v2/pet/" + id);
  }
}

module.exports = Petstore;
```

**Expected behavior**
Each test is added once to the report

**Screenshots**
![2024-06-07_09-28](https://github.com/allure-framework/allure-js/assets/16239820/6ce99933-8a04-4620-afee-87004ee0ca6d)

**Additional context**

allure: v2.29.0
allure-cucumberjs: 2.15.1
cucumber/cucumber: 10.8.0

**Comment by YakovL** [comment]
Note: you are mixing the [Suite-based hierarchy](https://allurereport.org/docs/gettingstarted-navigation/#suite-based-hierarchy):
```
  this.parentSuite("REST api");
  this.suite("Petstore");
```
with the [Behavior-based hierarchy](https://allurereport.org/docs/gettingstarted-navigation/#behavior-based-hierarchy):
```
  this.epic("REST api");
```
Which you probably don't want in the end, but this is not the source of the problem: commenting out just that line (as well as `this.label(LabelName.PACKAGE, "cucumber.features.petstore")`) doesn't remove the duplication. I've created a [repo](https://github.com/YakovL/allure-report-duplication-bug) with a minimal reproducible example.

Bug details:

- "REST api" parentSuite is created, as intended;
- inside it, unexpectedly, 2 suites are created: one named as requested by `this.suite` and another with the name of the Cucumber scenario;
- inside both suites, the same test (scenario) is shown, i.e. inside the unexpectedly added suite "Add pet", the same "Add pet" scenario is shown.

I'm not sure if [using await](https://github.com/allure-framework/allure-js/blob/main/packages/allure-cucumberjs/test/fixtures/support/runtime/legacy/labels.cjs) before `this.parentSuite` is required, but that didn't fix the issue in my case neither.

I've even [updated](https://github.com/YakovL/allure-report-duplication-bug/commit/6121dcde021348bb92299f85e20475ce3e3df226) `allure-cucumberjs` to `3.0.0-beta.3` ([relevant docs](https://github.com/allure-framework/allure-js/blob/main/packages/allure-cucumberjs/README.md)), but the bug is still reproduced.

**Comment by YakovL** [comment]
Narrowing the problem down..

- in the minimal case, 1 JSON is generated in allure-results (while if I add another scenario in the same .feature file, 2 files are generated);
- in the generated JSON, `.labels` has 2 `suite` values:

      "labels": [
        ...
        {
          "name": "suite",
          "value": "<name of the scenario>"
        },
        {
          "name": "parentSuite",
          "value": "REST api"
        },
        {
          "name": "suite",
          "value": "Petstore"
        }
      ],

So this is a problem of the `allure-cucumber` package, not the reporter. [Here's where the label is added](https://github.com/allure-framework/allure-js/blob/6295a36ae67cb0d19a0dcb3636eaafec8b50d4a6/packages/allure-cucumberjs/src/reporter.ts#L275): name of the scenario is always added as a SUITE label.

A proper fix would be to remove that whole bit:

    if (scenario) {
      result.labels!.push({
        name: LabelName.SUITE,
        value: scenario.name,
      });
    }

as:

- if a user sets their own suite, they get a duplicate in the report due to 2 `suite` labels;
- otherwise (since scenario names are unique), it creates an extra level of nesting (suite has the same name as the _only_ element in it, see the screen in the original issue).

Adding a PR for this...
